# Generated by Django 4.2.1 on 2023-08-09 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_register_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='login_Register',
        ),
    ]
