# Generated by Django 4.2.1 on 2023-08-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_register_login_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login_register',
            old_name='firstName',
            new_name='father',
        ),
        migrations.RenameField(
            model_name='login_register',
            old_name='lastName',
            new_name='mother',
        ),
    ]
